version: "2" # using 2 because 3 doesn't support extending

services:
  #TOKEN:^DC__NODE_APP
  #TOKEN:#DC__APP_NAME:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: #TOKEN:#DC__APP_NAME
    #TOKEN:^DC__NGINX
    depends_on:
      - "nginx"
    #TOKEN:$DC__NGINX
    environment:
      #TOKEN:^DC__MULTI_USER
      DATA_PATH: /home/node/app/data
      #TOKEN:$DC__MULTI_USER
      #TOKEN:^DC__NODE_CERTS
      NODE_EXTRA_CA_CERTS: /home/node/app/server/certs/localhost.crt
      #TOKEN:$DC__NODE_CERTS
      NODE_ENV: production
      #TOKEN:^DC__VHOST
      SERVER_PORT: ${VHOST__PORT__APP}
      #TOKEN:$DC__VHOST
      TZ: America/Los_Angeles
    #TOKEN:^DC__VHOST
      VHOST_PROXY_PORT: ${VHOST__PORT__PROXY}
    expose:
      - "${VHOST__PORT__APP}"
    #TOKEN:$DC__VHOST
    image: #TOKEN:#DC__USERNAME/#TOKEN:#DC__APP_NAME
    #TOKEN:^DC__PORTS
    ports:
      # Map Local port to the Container's exposed port
      - "3000:3000"
    #TOKEN:$DC__PORTS
    #TOKEN:^DC__VOLUMES
    volumes:
      #TOKEN:^DC__NODE_CERTS
      - "${PWD}/certs.localhost:/home/node/app/server/certs"
      #TOKEN:$DC__NODE_CERTS
      #TOKEN:^DC__MULTI_USER
      - "${PWD}/data:/home/node/app/data"
      #TOKEN:$DC__MULTI_USER
      # Uncomment to map Local assets
      # - "${PWD}/dist/public:/home/node/app/public"
      # - "${PWD}/dist/server:/home/node/app/server"
      # - "${PWD}/dist/utils:/home/node/app/utils"
      # - "${PWD}/dist/constants.js:/home/node/app/constants.js"
    #TOKEN:$DC__VOLUMES
  
  #TOKEN:$DC__NODE_APP
  #TOKEN:^DC__E2E
  e2e:
    build:
      context: ./e2e/
      dockerfile: Dockerfile
    # command: 'cypress run --browser chrome'
    container_name: e2e-#TOKEN:#DC__APP_NAME
    depends_on:
      - #TOKEN:#DC__APP_NAME
    environment:
      CYPRESS_baseUrl: http://host.docker.internal:3000
      # ELECTRON_ENABLE_LOGGING: 1 # view console logs from Browser (headless)
      # DEBUG: cypress:server:browsers:electron # view Electron internal logging
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ports:
      - "3001:3000"
    working_dir: /e2e
    volumes:
      - "${PWD}/e2e:/e2e"
      - "${PWD}/data:/app/data"
  
  #TOKEN:$DC__E2E
  #TOKEN:^DC__NGINX
  nginx:
    environment:
      # NOTE - Any template vars (prefixed with `TMP`) will be interpreted
      # statically. For example, if you wrap a value in quotes, those quotes
      # will be injected.
      #TOKEN:^DC__NGINX_SERVER
      - TMP__APP_PORT=${NGINX__PORT__APP__INTERNAL}
      - TMP__LOG_NAME=#TOKEN:#DC__LOG_NAME
      #TOKEN:$DC__NGINX_SERVER
      #TOKEN:^DC__VHOST
      - TMP__HOST_NAME=${VHOST__DOMAIN}
      - TMP__PORT__PROXY=${VHOST__PORT__PROXY_INTERNAL}
      #TOKEN:$DC__VHOST
    image: nginx:1.21.0-alpine
    ports:
      #TOKEN:^DC__NGINX_SERVER
      - "${NGINX__PORT__SERVER__HOST}:${NGINX__PORT__SERVER__INTERNAL}"
      - "${NGINX__PORT__APP__HOST}:${NGINX__PORT__APP__INTERNAL}"
      #TOKEN:$DC__NGINX_SERVER
      #TOKEN:^DC__VHOST_PORT
      - "${VHOST__PORT__PROXY}:${VHOST__PORT__PROXY_INTERNAL}"
      #TOKEN:$DC__VHOST_PORT
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/logs:/var/log/nginx
      # NOTE - Comment out the templates mount to stop generating files.
      - ./.docker/nginx/templates:/etc/nginx/templates
      #TOKEN:^DC__NGINX_SERVER
      - ./.docker/nginx/www:/var/www
      #TOKEN:$DC__NGINX_SERVER
      #TOKEN:^DC__VHOST_SECURE
      - "${PWD}/certs.${VHOST__DOMAIN}:/etc/nginx/certs"
      #TOKEN:$DC__VHOST_SECURE
  
  #TOKEN:$DC__NGINX
