##
# https://github.com/moby/moby/issues/31101#issuecomment-922378041
# Clarifies why there's no `version` prop, and why `extends` works regardless of
# what the docs.docker.com documentation says.
##

services:
  #TOKEN:#DC__APP_NAME:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: #TOKEN:#DC__APP_NAME
    #TOKEN:^DC__VHOST
    depends_on:
      - "nginx-proxy"
    #TOKEN:$DC__VHOST
    environment:
      DATA_PATH: /app_data
      #TOKEN:^DC__NODE_CERTS
      NODE_EXTRA_CA_CERTS: /app_certs/localhost.crt
      #TOKEN:$DC__NODE_CERTS
      #TOKEN:^DC__VHOST
      SERVER_PORT: ${VHOST__PORT__APP}
      #TOKEN:$DC__VHOST
      TZ: America/Los_Angeles
    #TOKEN:^DC__VHOST
      VHOST_PROXY_PORT: ${VHOST__PORT__PROXY}
      VIRTUAL_HOST: ${VHOST__DOMAIN}
      VIRTUAL_PORT: ${VHOST__PORT__APP}
    expose:
      - "${VHOST__PORT__APP}"
    #TOKEN:$DC__VHOST
    image: #TOKEN:#DC__USERNAME/#TOKEN:#DC__APP_NAME
    #TOKEN:^DC__PORTS
    ports:
      # Map Local port to the Container's exposed port
      - "3000:3000"
    #TOKEN:$DC__PORTS
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      #TOKEN:^DC__NODE_CERTS
      - type: bind
        source: "${PWD}/certs"
        target: "/app_certs"
      #TOKEN:$DC__NODE_CERTS
      - "${PWD}/.app_data:/app_data"
  
  #TOKEN:#DC__DEV_APP_NAME:
    extends: #TOKEN:#DC__APP_NAME # allows for just changing key pieces of data for development
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: #TOKEN:#DC__DEV_APP_NAME
    environment:
      NODE_ENV: development
    ports:
      #TOKEN:^DC__BSYNC
      # browserSync
      - "3001:3001"
      - "3002:3002"
      #TOKEN:^DC__WEB_SOCKET
      - "3003:3003"
      #TOKEN:$DC__WEB_SOCKET
      #TOKEN:$DC__BSYNC
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.docker/.vimrc:/home/node/.vimrc"
      - "${PWD}/.docker/.zshrc:/home/node/.zshrc"
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
  #TOKEN:^DC__E2E
  
  e2e-#TOKEN:#DC__APP_NAME:
    build:
      context: ./e2e/
      dockerfile: Dockerfile
    # command: 'cypress run --browser chrome'
    container_name: e2e-#TOKEN:#DC__APP_NAME
    depends_on:
      - #TOKEN:#DC__E2E_DEPENDS_ON
    # environment:
    #   # ELECTRON_ENABLE_LOGGING: 1 # view console logs from Browser (headless)
    #   # DEBUG: cypress:server:browsers:electron # view Electron internal logging
    hostname: cypresstests
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ports:
      - "3001:3000"
    privileged: true
    working_dir: /e2e
    volumes:
      - type: bind
        source: "${PWD}/.app_data"
        target: "/app_data"
      - "${PWD}/e2e:/e2e"
      - "${PWD}/src:/src"
  #TOKEN:$DC__E2E
  #TOKEN:^DC__VHOST
  
  nginx-proxy:
    environment:
      DISABLE_ACCESS_LOGS: "true"
    image: nginxproxy/nginx-proxy:alpine
    ports:
      #TOKEN:^DC__VHOST_NON_SECURE
      - "${VHOST__PORT__PROXY}:80"
      #TOKEN:$DC__VHOST_NON_SECURE
      #TOKEN:^DC__VHOST_SECURE
      - "${VHOST__PORT__PROXY}:443"
      #TOKEN:$DC__VHOST_SECURE
    volumes:
      #TOKEN:^DC__VHOST_SECURE
      - type: bind
        source: "${PWD}/certs.${VHOST__DOMAIN}"
        target: "/etc/nginx/certs"
      #TOKEN:$DC__VHOST_SECURE
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Uncomment to view the generated config
      # - "${PWD}/.docker/vhost/conf.d:/etc/nginx/conf.d"
  #TOKEN:$DC__VHOST
  #TOKEN:^DC__E2E_PROXY
  
  proxy:
    container_name: #TOKEN:#DC__APP_NAME_proxy
    environment:
      CRT: /home/node/certs/localhost.crt
      KEY: /home/node/certs/localhost.key
      MOCKS_PATH: /home/node/proxy/cache
      NODE_EXTRA_CA_CERTS: /home/node/certs/localhost-CA.crt
    image: theonewhoknocks/nodejs-proxy
    ports:
      - 9002:80
      - 9229:9229
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      # cert is required to handle any secure traffic
      - type: bind
        source: "${PWD}/certs"
        target: "/home/node/certs"
      - type: bind
        source: "${PWD}/e2e/cypress/fixtures/cache"
        target: "/home/node/proxy/cache"
      - "${PWD}/proxy/matcher.js:/home/node/proxy/matcher.js"
  
  proxied-app:
    extends: #TOKEN:#DC__APP_NAME
    command: node --inspect=0.0.0.0:9230 /home/node/app/server
    container_name: proxied_app
    depends_on:
      - proxy
    environment:
      # proxy stuff
      #TOKEN:^DC__NODE_CERTS
      NODE_EXTRA_CA_CERTS: /home/node/certs/localhost.crt
      #TOKEN:$DC__NODE_CERTS
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # Using this to get around error "reason: Hostname/IP does not match certificate's altnames: Host: <HOST>. is not in the cert's altnames: DNS:localhost
    links:
      - "proxy:opentdb.com"
    ports:
      - 9230:9230
    #TOKEN:^DC__NODE_CERTS
    volumes:
      - type: bind
        source: "${PWD}/certs"
        target: "/home/node/certs"
    #TOKEN:$DC__NODE_CERTS
  #TOKEN:$DC__E2E_PROXY
