# NOTE:
# - Using a separate compose file because the `VOL_` variables are only defined
#   via the test-runner, and can't define volumes via CLI since `up` is required
#   instead of `run` to allow for `--abort-on-container-exit` to work. Other
#   missing variables are ignored, but for some reason there's a yaml validation
#   check that fails for missing volume definitions even if I'm not trying to
#   run the container with the missing variables.
# - The context for `PWD` is the repo root since the test-runner is run via npm
#   in the project root.

services:
  #TOKEN:#DC__APP_NAME-test:
    extends:
      file: "${PWD}/docker-compose.yml"
      service: #TOKEN:#DC__EXT_APP_NAME
    container_name: #TOKEN:#DC__APP_NAME-test
    environment:
      # DATA_PATH: /test/data.json
      #TOKEN:^DC__SECURE
      NODE_EXTRA_CA_CERTS: /home/node/certs/tests.crt
      #TOKEN:#DC__SECURE
    healthcheck: # required for the test container to start
      interval: "3s"
      retries: 3
      start_interval: "2s"
      test: wget --no-verbose --tries=1 --spider --no-check-certificate #TOKEN:#DC__PROTOCOL://localhost:3000 || exit 1
      timeout: "2s"
    hostname: tests.lan # domain name (usually assigned via container name)
    # volumes:
    #   - "${PWD}/e2e/tests/fixtures/data.json:/test/data.json:r"
  
  #TOKEN:#DC__APP_NAME-e2e:
    build:
      context: "${PWD}/e2e/"
      dockerfile: Dockerfile
    command: $CMD
    container_name: #TOKEN:#DC__APP_NAME-e2e
    depends_on:
      #TOKEN:#DC__E2E_DEPENDS_ON:
        condition: service_healthy
    environment:
      BASE_URL: "#TOKEN:#DC__PROTOCOL://tests.lan:3000"
      DISPLAY: $TEST_DISPLAY
    hostname: e2etests
    ipc: host # Using `--ipc=host` is recommended when using Chrome (Docker docs). Chrome can run out of memory without this flag.
    ports:
      - "3001:3000"
    security_opt:
      - "seccomp:${PWD}/e2e/seccomp_profile.json"
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      #TOKEN:^DC__SECURE
      - "${PWD}/certs:/certs:r"
      #TOKEN:#DC__SECURE
      - "${PWD}/e2e:/e2e"
      - "${PWD}/src/constants.js:/node_modules/@src/constants.js:r" # map local modules to the fake `@src` parent
      - $VOL_DBUS
      - $VOL_X11
  #TOKEN:^DC__E2E_PROXY
  
  proxy:
    extends: 
      file: "${PWD}/docker-compose.yml"
      service: proxy
  
  proxied-app: 
    extends:
      file: "${PWD}/docker-compose.yml"
      service: proxied-app
    hostname: #TOKEN:#DC__APP_NAME # domain name (usually assigned via container name)
  #TOKEN:$DC__E2E_PROXY
